# ===========================================
# GO-API - Docker Compose para EasyPanel
# ===========================================
#
# PORTAS:
# - Frontend: 3002
# - API: 3001 (Nginx CORS -> Node 3002 interno)
# - PostgreSQL: 5432
#
# CORS já configurado para x-api-key funcionar!
# Não precisa mudar nada no Easypanel.
#
# PASSO A PASSO PARA QUE RODE DIREITO
#
# 1º PASSO
# Va em dominios dentro do projeto o primeiro dominio
# você coloca exemplo assim: frontend-usego.pdjn0x.easypanel.host
# Porta você verifica se já ta usando a 3002 se não repita
# Em Compose Service você coloca frontend apenas isso e salva
#
# 2º PASSO
# Clique encima do dominio frontend-usego.pdjn0x.easypanel.host ele vai
# copiar automaticamente e você clica em Adicionar Dominio e em
# Host você vai colocar o dominio la dentro porem vai mudar para
# api-usego.pdjn0x.easypanel.host Porta você verifica se já ta usando 
# a 3001 se não repita e em Compose Service você coloca api apenas isso e salva
# e continua preenchendo os campos abaixo:
# ===========================================

services:
  # =========================================
  # FRONTEND - Next.js (porta 3002)
  # =========================================
  frontend:
    build:
      context: https://github.com/othonrighettirr/usego.git#main #NÃO MECHER
      dockerfile: frontend/Dockerfile
    container_name: gopro-frontend
    restart: always
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - ADMIN_EMAIL= #COLOQUE SEU EMAIL
      - ADMIN_PASSWORD= #SENHA DE ACESSO PAINEL
      # API_URL interno (Docker network) - usado pelo proxy server-side
      - API_URL=http://api:3001
      # URL pública da API (para referência, mas proxy evita CORS)
      - NEXT_PUBLIC_API_URL= #COLOQUE O DOMINIO QUE VOCÊ CRIOU PARA API
    depends_on:
      - api
    networks:
      - gopro-network

  # =========================================
  # API - NestJS + Baileys + Nginx CORS (porta 3001)
  # =========================================
  api:
    build:
      context: https://github.com/othonrighettirr/usego.git#main #NÃO MECHER
      dockerfile: api/Dockerfile
    container_name: gopro-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3002
      - NODE_ENV=production
      - DATABASE_URL=postgresql://goapi:goapi_secret_2024@postgres:5432/goapi?schema=public
      - JWT_SECRET= #SERE A SENHA EM https://jwtsecrets.com/
      - JWT_EXPIRES_IN=3000000d
      - CORS_ORIGIN=*
      - ADMIN_EMAIL= #COLOQUE SEU EMAIL
      - ADMIN_PASSWORD= #SENHA DE ACESSO PAINEL
      # ========================================
      # LICENCIAMENTO - CONFIGURAR AQUI
      # ========================================
      - LICENSE_SERVER=https://usego.com.br
      - LICENSE_KEY= #COLOQUE A LICENÇA GERADA EM WWW.USEGO.COM.BR
      - MACHINE_ID= #COLOQUE A MESMA QUE É GERADA COM A LICENÇA
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - sessions_data:/app/sessions
      - license_data:/app/license
    networks:
      - gopro-network

  # =========================================
  # POSTGRES - Banco de Dados (porta 5432)
  # =========================================
  postgres:
    image: postgres:15-alpine
    container_name: gopro-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=goapi
      - POSTGRES_PASSWORD=goapi_secret_2024
      - POSTGRES_DB=goapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goapi -d goapi"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - gopro-network

volumes:
  postgres_data:
  sessions_data:
  license_data:

networks:
  gopro-network:
    driver: bridge