version: '3.8'

# GO-API - Stack Portainer (sem SSL)
# PostgreSQL e Redis independentes
# Cole este conteúdo no Portainer > Stacks > Add Stack

services:
  postgres:
    image: postgres:15-alpine
    container_name: goapi-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: goapi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-goapi123}
      POSTGRES_DB: goapi
    volumes:
      - goapi_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goapi -d goapi"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - goapi-net

  redis:
    image: redis:7-alpine
    container_name: goapi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - goapi_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - goapi-net

  backend:
    image: usegoapi/gopro-backend:latest
    container_name: goapi-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://goapi:${POSTGRES_PASSWORD:-goapi123}@postgres:5432/goapi
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-mude-esta-chave-em-producao}
      JWT_EXPIRES_IN: 7d
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@goapi.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      NODE_ENV: production
    volumes:
      - goapi_sessions:/app/sessions
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - goapi-net

  frontend:
    image: usegoapi/gopro-frontend:latest
    container_name: goapi-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${API_URL:-http://localhost:3000}
    depends_on:
      - backend
    networks:
      - goapi-net

volumes:
  goapi_postgres:
  goapi_redis:
  goapi_sessions:

networks:
  goapi-net:
    driver: bridge
